apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kagent
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/kagent-dev/kagent/helm/kagent
  ref:
    semver: ">=0.0.1"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: kagent-crds
      namespace: flux-system
  targetNamespace: kagent
  chartRef:
    kind: OCIRepository
    name: kagent
    namespace: flux-system
  install:
    createNamespace: true
  values:
    tools:
      querydoc:
        enabled: false
    agents:
      cilium-policy-agent:
        enabled: false
      cilium-manager-agent:
        enabled: false
      cilium-debug-agent:
        enabled: false
      promql-agent:
        enabled: false
      istio-agent:
        enabled: false
      istio-policy-agent:
        enabled: false
      istio-manager-agent:
        enabled: false
    providers:
      openAI:
        apiKey: OPENAI_API_KEY