apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: flux-config-image
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 5m
spec:
  type: OCIArtifactTag
  url: oci://ghcr.io/den-vasyliev/a-box/flux-config
  filter:
    includeTag: ^\d+\.\d+\.\d+$
    limit: 1
  defaultValues:
    tag: "0.1.0"
---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: flux-config
  namespace: flux-system
spec:
  inputsFrom:
  - kind: ResourceSetInputProvider
    name: flux-config-image
  resources:
  - apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: OCIRepository
    metadata:
      name: flux-config
      namespace: flux-system
    spec:
      interval: 5m
      url: oci://ghcr.io/den-vasyliev/a-box/flux-config
      ref:
        tag: << inputs.tag >>
  - apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: flux-config
      namespace: flux-system
    spec:
      interval: 5m
      sourceRef:
        kind: OCIRepository
        name: flux-config
      path: ./
      prune: true
      wait: true
